apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      app: jenkins-$(CHE_WORKSPACE_ID)
    name: jenkins-$(CHE_WORKSPACE_ID)
  spec:
    containers:
    - image: sonikro/jenkins-codeready-workspace:latest
      imagePullPolicy: Always
      name: jenkins-$(CHE_WORKSPACE_ID)
      ports:
      - containerPort: 8080
        protocol: TCP
      - containerPort: 50000
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/jenkins_home
        name: jenkins-codeready-workspace
      - mountPath: /var/run/docker.sock
        name: socket
    dnsPolicy: ClusterFirst
    imagePullSecrets:
    - name: default-dockercfg-r7kmd
    nodeName: localhost
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    volumes:
    - emptyDir: {}
      name: jenkins-codeready-workspace
    - hostPath:
        path: /var/run/docker.sock
        type: ""
      name: socket
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: jenkins-$(CHE_WORKSPACE_ID)
    name: jenkins-$(CHE_WORKSPACE_ID)
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 50000-tcp
      port: 50000
      protocol: TCP
      targetPort: 50000
    selector:
      app: jenkins-$(CHE_WORKSPACE_ID)
    sessionAffinity: None
    type: ClusterIP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: jenkins-$(CHE_WORKSPACE_ID)
    name: jenkins-$(CHE_WORKSPACE_ID)
  spec:
    host: jenkins-$(CHE_WORKSPACE_ID).openshift.sonikro.com
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: jenkins-$(CHE_WORKSPACE_ID)
      weight: 100
    wildcardPolicy: None
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
