apiVersion: v1
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: jenkins-codeready-worksp
    name: jenkins-codeready-worksp
  spec:
    replicas: 1
    selector:
      app: jenkins-codeready-worksp
      deploymentconfig: jenkins-codeready-worksp
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: jenkins-codeready-worksp
          deploymentconfig: jenkins-codeready-worksp
      spec:
        containers:
        - image: sonikro/jenkins-codeready-workspace:latest
          imagePullPolicy: Always
          name: jenkins-codeready-worksp
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 50000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/jenkins_home
            name: jenkins-codeready-worksp-1
          - mountPath: /var/run/docker.sock
            name: socket
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: jenkins-codeready-worksp-1
        - hostPath:
            path: /var/run/docker.sock
            type: ""
          name: socket
    test: false
    triggers:
    - type: ConfigChange
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
